### ISSUE TITLE
Chapter 6: Creating Service LB Pending

### ISSUE THREAD

**Issue by black-lotus** [nigelpoulton/TKB#9]
**Chapter:** 6: Kubernetes Deployments
**Section:** Create a Deployment

Service status
```
$ kubectl get svc
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP      10.96.0.1      <none>        443/TCP          6d18h
lb-svc       LoadBalancer   10.96.24.176   <pending>     8080:32078/TCP   4m43s
```

Warning
```
Error syncing load balancer: failed to ensure load balancer: failed to create containers kindccm-IX6NQO744TR2ZMPA7XUQYN2NTFWEFSOVPVNIPRSE [--detach --tty --label io.x-k8s.cloud-provider-kind.cluster=desktop --label io.x-k8s.cloud-provider-kind.loadbalancer.name=desktop/default/lb-svc --label io.kubernetes.pod.namespace=kube-system --net kind --init=false --hostname kindccm-IX6NQO744TR2ZMPA7XUQYN2NTFWEFSOVPVNIPRSE --restart=on-failure --publish=0.0.0.0:8080:8080/TCP envoyproxy/envoy:v1.32.0 bash -c echo -en 'node: cluster: cloud-provider-kind id: cloud-provider-kind-id dynamic_resources: cds_config: resource_api_version: V3 path: /home/envoy/cds.yaml lds_config: resource_api_version: V3 path: /home/envoy/lds.yaml admin: access_log_path: /dev/stdout address: socket_address: address: 0.0.0.0 port_value: 10000 ' > /home/envoy/envoy.yaml && touch /home/envoy/cds.yaml && touch /home/envoy/lds.yaml && while true; do envoy -c /home/envoy/envoy.yaml && break; sleep 1; done]: exit status 125
```

The suspected issue is a port conflict, as both containers.containerPort and loadBalancer.port use 8080.

I changed the deployments/lb.yml and perfectly works
```
apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 9999
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-world
```

Service status
```
kubectl get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP      10.96.0.1       <none>        443/TCP          6d18h
lb-svc       LoadBalancer   10.96.142.105   172.18.0.9    9999:32704/TCP   13s
```
